name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # Change to your desired region

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: |
          docker build -t your-docker-image .
          docker tag your-docker-image:latest your-repo-url:latest
          docker push your-repo-url:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster hello-world-cluster --service hello-world-service --force-new-deployment
